version: 0.0
os: linux
files:
  - source: s3://codepipeline-us-west-2-598491907540/DemoPipeline1/BuildArtif/hwh7shJ
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/stop_apache_server.sh
      timeout: 300
      runas: root
      
  AfterInstall:
    - location: scripts/start_apache_server.sh
      timeout: 300
      runas: root
