version: 0.2


phases:
  install:
    runtime-versions:
        nodejs: 14
    commands:
        - echo Installing source NPM dependencies...
        - npm install
        - npm install -g @angular/cli
  build:
    commands:
        - echo Build started 
        - ng build
  post_build:
    commands:
      - echo "Unzipping artifacts..."
     #  unzip -q 
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
